### ISSUE TITLE
missing documentation for webserver setup

### ISSUE THREAD

**Issue by fredleger** [realshadow/satis-control-panel#10]
I think it miss some infos about how to configure exactly your webserver.
How the DocumentRoot is setup ? some rewrite rules ? laravel specific setup ?

After many hours i ended up with a 404 on /api ans i feel a bit frustrated

**Comment by antonkomarev** [comment]
@fredleger Isn't it working with default Laravel config?

**Comment by fredleger** [comment]
It look to have some progress where do you point the documentroot ?
public/ ?
I think it's good to mention in the docs :-)

Le 29/02/2016 17:52, Pe Ell a écrit :

> @fredleger https://github.com/fredleger Isn't it working with
> default Laravel config?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realshadow/satis-control-panel/issues/10#issuecomment-190285676.

## 

Frederic Leger
06 52 77 53 54

Mes infos PGP : http://frederic.leger.people.webofmars.fr/index.php?pages/infos

**Comment by antonkomarev** [comment]
Yes, root pointed to `/public` folder, not the `/public/public` one.

```
root /var/www/satis-control-panel/public;
```

And here is root URI:

```
 location / {
    index index.php index.html index.htm;
    try_files $uri $uri/ /index.php?$query_string;
}
```

After that there should be available URL:

http://your.domain/control-panel

**Comment by realshadow** [comment]
Hey, I have added some example vhosts for both apache and vhost configuration into readme

**Comment by fredleger** [comment]
Great !
Thanks.

Le 29/02/2016 21:44, Lukáš Homza a écrit :

> Hey, I have added some example vhosts for both apache and vhost
> configuration into readme
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realshadow/satis-control-panel/issues/10#issuecomment-190379261.

## 

Frederic Leger
06 52 77 53 54

Mes infos PGP : http://frederic.leger.people.webofmars.fr/index.php?pages/infos
