### ISSUE TITLE
node server.js need to support SSL as well

### ISSUE THREAD

**Issue by fredleger** [realshadow/satis-control-panel#12]
We installed satis-control-panel for using it with composer. 
It look like it's easier to have it using https unless you want to always have ""secure-http": "false"" in the composer.lock.
So we put the site under SSL with a self-signed cert but now is the thing : the node server.js is not able to handle https on requests. So either you d'ont use async builds, either you have a Mixed content error : 

![2016-03-09 15_35_46-new notification](https://cloud.githubusercontent.com/assets/2778741/13638497/d12d1d1e-e60c-11e5-89a7-dd8155ee5d5e.png)

Is there a way where the node server can handle https ?

**Comment by realshadow** [comment]
You can change the node server configuration `node/config.json`.

I will put some info about it in readme and create a .dist config file so future updates won't break user changes.

**Comment by realshadow** [comment]
You can change the node server configuration in `node/config.json`.

I will put some info about it in readme and create a .dist config file so future updates won't break local modifications.

If that won't be enough (as I have currently no way to test this), I will modify the node server so it can use SSL.

You can find more info about this here http://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js, in case the first option won't work and you are willing to test it :)

**Comment by fredleger** [comment]
As far as i understand it you also need to alter code in roder to add the certificates and all the ssl params, no ?

**Comment by fredleger** [comment]
Tried "host": "http**s**://satis.example.com" in node/config.json, and didn't changed anything. It's where the error screeshoot came actually so i do think there is some code mofication to do in order to have it working in server.js at least to require the https module

**Comment by realshadow** [comment]
Yes, it requires code modification. Something along the lines of http://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js. I will look into it during holidays :)

**Comment by neilime** [comment]
I've made a PR that can maybe fix this issue : #14

**Comment by realshadow** [comment]
@neilime PR has been merged into 1.0.4
