### ISSUE TITLE
Dist satis.json and generated satis fails schema validation

### ISSUE THREAD

**Issue by LavaToaster** [realshadow/satis-control-panel#13]
In the [satis](https://raw.githubusercontent.com/realshadow/satis-control-panel/master/resources/satis.json.dist) configuration, the require property is an array by default `"require":[]`, however, this fails validation as the schema requires it to be an object `"require":{}`. 

https://github.com/composer/satis/blob/master/res/satis-schema.json

**Comment by neilime** [comment]
I had the same issue.

**Comment by drabajs** [comment]
The same... even the json file is valid in fact.

**Comment by jakubdrabik** [comment]
The same... event the json is valid in fact after checking it.

**Comment by jakubdrabik** [comment]
ConfigMirror is adding require: [] as a default value for private repositories which is wrong because it is an invalid value, require must be object ({}).

**Comment by realshadow** [comment]
Yes, I am aware of that, I will look into it during holidays

**Comment by jgedarovich** [comment]
I had the same issue, can confirm #13 fixes this for me after trying it out

**Comment by realshadow** [comment]
@neilime PR has been merged into 1.0.4
