### ISSUE TITLE
Output from proccess

### ISSUE THREAD

**Issue by jakubdrabik** [realshadow/satis-control-panel#16]
Processed build commands are not logged, only empty log files are created even after manual satis triggering there is an output in cli.

**Comment by realshadow** [comment]
What OS do you have?

I have noticed that on some systems the output is not correctly redirected

**Comment by jakubdrabik** [comment]
Debian 7.9

2016-03-31 15:50 GMT+02:00 Lukáš Homza notifications@github.com:
