### ISSUE TITLE
Can't add VCS repositories with ssh acces

### ISSUE THREAD

**Issue by jdoubleu** [realshadow/satis-control-panel#17]
When I want to add a git repository using ssh instead of http(s) the form denies it.
I guess this is because the regexp checks for http(s).
Satis still can manage git repositories over ssh.

**Comment by jdoubleu** [comment]
Okay, I figured out that the RegExp in `satis-control-panel/resources/assets/typescript/helpers/Validator.ts` doesn't allow username (and password) in uri when no protocol is given.

So the RegExp needs to be changed or another RegExp needs to be used when package type `vcs` is selected.
Changing the RegExp could lead to inconsistent of url's for other composer package types. 

See https://regex101.com/r/kY5vJ9/2 for failing regexp,
check out this regexp https://www.debuggex.com/r/H4kRw1G0YPyBFjfm for git uri's

**Comment by realshadow** [comment]
I am aware that SSH is currently not supported as I did not need it, but I will look at it this week

**Comment by vitman** [comment]
looks like this is still an issue.
And ssh is really required for me as well

**Comment by vitman** [comment]
Do we need to do something more than update regexp?

**Comment by realshadow** [comment]
Theoretically yes

**Comment by vitman** [comment]
and what steps it should be?
Is there any chance that you will be able to look into it?
Probably i can try to prepare a PR.

**Comment by realshadow** [comment]
Part of 1.0.5 release. Try it please

**Comment by vitman** [comment]
Thanks! Is there guidelines on how to update existing installation?

My steps:

> git pull origin master
composer update
rm -rf /var/www/html/satis/bootstrap/cache/compiled.php
php artisan optimize

**Comment by realshadow** [comment]
Thats about it :)
