### ISSUE TITLE
npm run server

### ISSUE THREAD

**Issue by MiteshShah** [realshadow/satis-control-panel#18]
```
[root@localhost satis-control-panel]# npm run server

> @ server /var/www/vhosts/satis.example.com/satis-control-panel
> node node/server.js


fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory ''
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/var/www/vhosts/satis.example.com/satis-control-panel/node/server.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

```
[root@localhost satis-control-panel]# node -v
v0.10.42
```

```
[root@localhost satis-control-panel]# npm -v
1.3.6
```

**Comment by realshadow** [comment]
Looks like you have _https_ in your `node/config.json` set for host. In that case you need to provide ssl certificates.

In the meantime I will make the error reporting more verbose

**Comment by realshadow** [comment]
Looks like https was set as default in node config. Might have gotten there during the PR for SSL support. Sorry for that, its fixed in master now

**Comment by MiteshShah** [comment]
@realshadow Now above issue gone 

But when i add repo its say

No repositories were found.
Encountered unexpected error. Check logs for details.
×
<img width="645" alt="screen shot 2016-04-12 at 10 43 51 am" src="https://cloud.githubusercontent.com/assets/1223371/14466276/b4e2e6bc-009b-11e6-94a5-cf7bf07df090.png">

**Comment by realshadow** [comment]
This seems to be a problem with webserver/htaccess settings.

Are you running under Apache/Nginx or Laravel server.php?

**Comment by MiteshShah** [comment]
Apache with no modification to any htaccess

**Comment by realshadow** [comment]
Errors like this cleary mean something is wrong in .htaccess or vhost settings, but I am not sure how I can help you from here...

Something similer has been discussed here - in issue #2 , maybe that might be the issue?
