### ISSUE TITLE
Type error: Argument 1 passed to App\Satis\ConfigManager::_addOrUpdatePackage() must be an instance of App\Satis\Collections\PackageCollection, null given

### ISSUE THREAD

**Issue by aedart** [realshadow/satis-control-panel#19]
After installing the application, and attempted to add a public package (from packagist), I received this error;

```
Type error: Argument 1 passed to App\Satis\ConfigManager::_addOrUpdatePackage() must be an instance of App\Satis\Collections\PackageCollection, null given
```

As far as I can see, it appears that the `\App\Satis\Model\Config` returns a `null` for `getRepositories`.
Am I missing something in the configuration?

**Comment by DaanMeijer** [comment]
I solved this by adding `"require":[]` to resources/satis.json.

**Comment by aedart** [comment]
Ty mate :)
