### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by d-lamers** [realshadow/satis-control-panel#20]
When trying to install I eventually get an error

Running
`composer create-project realshadow/satis-control-panel`
Throws

```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/dlamers/satis-control-panel/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
```

It is thrown right after composer fires php artisan optimize

**Comment by realshadow** [comment]
That is a Laravel related problem where an exception is thrown before the logger is registered

**Comment by netbrothers-tr** [comment]
I had the same one and was able to solve it by enabling a lot of PHP modules.
