### ISSUE TITLE
problem connecting to api 

### ISSUE THREAD

**Issue by dukeDanjou** [realshadow/satis-control-panel#21]
Hello i ve made alll my configuration but I end up with 404 not found for both the UI or a curl request  to the api.

I m using apache2 to host statis-control-panel my apache virtual host configurations is 

`
<VirtualHost *:9001>
        ServerAdmin webmaster@localhost
        ServerName satis
        DocumentRoot /var/www/satis
        ErrorLog ${APACHE_LOG_DIR}/error_satis.log
        CustomLog ${APACHE_LOG_DIR}/access_satis.log combined
</VirtualHost>
`

with a symbolic link satis -> /opt/satis-control-panel/public/

Node server is working fine and can acces the UI at http://my.domain/control-panel

but i get a 
POST http://my.domain:9001/control-panel/api/package 404 (Not Found)

**Comment by realshadow** [comment]
Hey,

document root should point to `public` directory inside your current directory, so it should be 
`/var/www/satis/public`

**Comment by dukeDanjou** [comment]
hi thanks for the answer the problem was at the allow at apache configuration :

`<Directory /var/www/satis>
        Options Indexes FollowSymLinks
        **AllowOverride All**
        Require all granted
</Directory>`

and then you need 
`a2enmod rewrite`

follow by

`service apache2 restart `

otherwise .htaccess are not used and their is no redirect to index.php

hope that help people 

one last question should we have access to the satis-control-panel/public ? 

because in the front UI their is a link to it  "Satis - Composer Repository"  but the .htaccess is set to 
Options -Indexes  instead of Options +Indexes

I don't know the expected behaviour but if i don't  change .htacess file i get a 403 forbidden when i click on "Satis - Composer Repository"

**Comment by realshadow** [comment]
Sorry, I missed your reply...

The **document root**  in your virtual host configuration should point to the **public** folder. That should resolve all the other problems with .htaccess, etc.
