### ISSUE TITLE
Update Satis release

### ISSUE THREAD

**Issue by rpwashburn** [realshadow/satis-control-panel#23]
It seems satis-control-panel is currently composering in "version": "1.0.0-alpha2" of Satis. 

As far as I can tell, this version is showing symptoms of [#377](https://github.com/composer/satis/issues/377) and was resolved with [#378](https://github.com/composer/satis/pull/378). It is trying to mirror all of packagist when I only want private repositories. 

I have asked them to issue a new release where this bug has been fixed, 1.0.0-alpha3. I have updated locally and it seems to have fixed this issue, but I am not certain if it is compatible.

**Comment by realshadow** [comment]
Ah, that would explain why it happened when I updated to it. I will try to update it later tonight. Thanks for the info

**Comment by realshadow** [comment]
I have updated Satis to alpha3 in the 1.0.6 release.

**Comment by vitman** [comment]
And now control panel is not working properly:)

PHP Warning:  require(/var/www/html/satis/bin/../vendor/composer/satis/src/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/satis/bin/satis on line 7
PHP Fatal error:  require(): Failed opening required '/var/www/html/satis/bin/../vendor/composer/satis/src/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/html/satis/bin/satis on line 7

bootstrap file was removed
