### ISSUE TITLE
Satis version was updated with errors

### ISSUE THREAD

**Issue by vitman** [realshadow/satis-control-panel#24]
Satis version was updated and now control panel is not working properly:)

PHP Warning: require(/var/www/html/satis/bin/../vendor/composer/satis/src/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/satis/bin/satis on line 7
PHP Fatal error: require(): Failed opening required '/var/www/html/satis/bin/../vendor/composer/satis/src/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/html/satis/bin/satis on line 7

bootstrap file was removed in latest satis release

**Comment by realshadow** [comment]
Sorry about that... Nothing can be as easy as you want it to be.

It should work with newest repository version

**Comment by vitman** [comment]
https://github.com/realshadow/satis-control-panel/blob/master/config/satis.php looks like 'ssh' needs to be added here as well

**Comment by vitman** [comment]
Thanks for your work!

**Comment by realshadow** [comment]
Ssh does not need to be added there. Event if your package is downloaded via ssh it still is VCS type. See https://getcomposer.org/doc/05-repositories.md#types
