### ISSUE TITLE
Types of `path` and `artifact` can't work because of URL validation

### ISSUE THREAD

**Issue by mattzuba** [realshadow/satis-control-panel#27]
As the title states, the path (/local/path/to/repo) won't validate the with the URL validation when trying to use Path or Artifact types.

I'd recommend dropping the URL validation all together and let the user assume they are entering what they need.  URL validation also currently requires a URL ending in .git, which precludes Mercurial repos from working.

**Comment by realshadow** [comment]
I have dropped the validation. It was partially dropped in one of the previous commits anyway. Git URL validation was intentional. I don't have any Mercurial repository to test this with. I have also resolved #28 .

Do you mind trying this in master branch first?

**Comment by mattzuba** [comment]
Thanks for the speedy commits and fixes, those seem to do it for me for now!  After pulling those changes and adding an 'hg' type to the config, I can pull in Mercurial repos now.  If you don't mind PR's, I may submit a few as my company uses this a little more.

**Comment by realshadow** [comment]
Great. Feel free to submit any PR
