### ISSUE TITLE
Error when trying to build repository

### ISSUE THREAD

**Issue by antonkomarev** [realshadow/satis-control-panel#5]
Every time when trying to build added VCS exception raising:

> [Composer\Json\JsonValidationException]                       
> 
>   The json config file does not match the expected JSON schema  
> 
> Exception trace:
>  () at /home/ell/Development/satis-control-panel/vendor/composer/satis/src/Composer/Satis/Command/BuildCommand.php:282
>  Composer\Satis\Command\BuildCommand->check() at /home/ell/Development/satis-control-panel/vendor/composer/satis/src/Composer/Satis/Command/BuildCommand.php:128
>  Composer\Satis\Command\BuildCommand->execute() at /home/ell/Development/satis-control-panel/vendor/symfony/console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at /home/ell/Development/satis-control-panel/vendor/symfony/console/Application.php:841
>  Symfony\Component\Console\Application->doRunCommand() at /home/ell/Development/satis-control-panel/vendor/symfony/console/Application.php:189
>  Symfony\Component\Console\Application->doRun() at /home/ell/Development/satis-control-panel/vendor/composer/satis/src/Composer/Satis/Console/Application.php:52
>  Composer\Satis\Console\Application->doRun() at /home/ell/Development/satis-control-panel/vendor/symfony/console/Application.php:120
>  Symfony\Component\Console\Application->run() at /home/ell/Development/satis-control-panel/bin/satis:26
> 
> build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--] [<file>] [<output-dir>] [<packages>]...

**Comment by realshadow** [comment]
Can I see your config file please?

**Comment by antonkomarev** [comment]
They are pretty default ones:

**Satis**

``` php
<?php

$filesystem = new \Illuminate\Filesystem\Filesystem();

$sharedConfig = json_decode($filesystem->get(base_path('node/config.json')), true);

return [
    'config' => base_path(env('SATIS_CONFIG', 'resources' . DIRECTORY_SEPARATOR . 'satis.json')),
    'composer_home' => base_path(env('COMPOSER_HOME', 'storage' . DIRECTORY_SEPARATOR . 'composer')),
    'composer_cache' => base_path(env('COMPOSER_HOME', 'storage' . DIRECTORY_SEPARATOR . 'composer/cache')),

    'memory_limit' => '2G',
    'build_verbosity' => 'vvv',

    'private_repository' => 'private',
    'public_repository' => 'public',

    'proxy' => [
        'http' => env('SATIS_HTTP_PROXY', null),
        'https' => env('SATIS_HTTPS_PROXY', null)
    ],

    /**
     *
     * Edit these options at your own risk
     *
     **/
    'default_repository_type' => 'vcs',

    'repository_types' => [
        'vcs', 'pear', 'composer', 'artifact', 'path'
    ],

    'build_directory' => base_path('public'),

    'public_mirror' => storage_path('app' . DIRECTORY_SEPARATOR . 'public.json'),
    'private_mirror' => storage_path('app' . DIRECTORY_SEPARATOR . 'private.json'),

    'lock' => base_path($sharedConfig['lock_file']),

    'node' => $sharedConfig,

    'sync_timeout' => 120,
];
```

**.env**

``` .env
APP_ENV=develop
APP_DEBUG=true
APP_KEY=mykey

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
```

**Comment by realshadow** [comment]
Sorry, I meant `satis.json` file

**Comment by antonkomarev** [comment]
``` json
{
    "name": "CyberCog Package Manager",
    "homepage": "http:\/\/localhost:8000",
    "require": {
        "cybercog\/laravel-service-provider": "*",
        "cybercog\/yii2-google-analytics": "*",
        "cybercog\/yii2-twittable": "*",
        "cybercog\/yii2-wschat": "*"
    },
    "require-all": false,
    "require-dependencies": true,
    "require-dev-dependencies": false,
    "archive": {
        "directory": "dist",
        "format": "tar",
        "skip-dev": true
    }
}
```

**Comment by realshadow** [comment]
I think I know where the problem is. 

Since the idea is to execute build directly from the UI, correct satis configuration for private/public packages is generated upon UI change. But that wasn't the case for build, I fixed that. Which I assume was the problem here.

Correct configuration can be also created with `php artisan satis:make:config` command.
